<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.34">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Data wrangling – Applied Geodata Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./data_vis.html" rel="next">
<link href="./data_variety.html" rel="prev">
<link href="././figures/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-c8ad9e5dbd60b7b70b38521ab19b7da4.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-befe23ebd2f54d8af2c8a89d1a1611f1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-c8ad9e5dbd60b7b70b38521ab19b7da4.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5580b768968c173edbcabd2ef8ecb882.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-ce530c4fc5b35f77c508c3bfad3cc1ab.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-5580b768968c173edbcabd2ef8ecb882.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta name="twitter:title" content="7&nbsp; Data wrangling – Applied Geodata Science">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="data_wrangling_files/figure-html/unnamed-chunk-13-1.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title"></span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://github.com/geco-bern/agds_book/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./data_wrangling.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Data wrangling</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./primers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Primers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reproducible_workflows.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Reusable workflows</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./code_management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Code management</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./open_science.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Open science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_variety.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data variety</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_wrangling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Data wrangling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_vis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Data visualisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression and classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./supervised_ml_I.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Supervised machine learning I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./supervised_ml_II.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Supervised machine learning II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randomforest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Random Forest</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interpretable-ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Interpretable Machine Learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives"><span class="header-section-number">7.1</span> Learning objectives</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">7.2</span> Setup</a></li>
  <li><a href="#tutorial" id="toc-tutorial" class="nav-link" data-scroll-target="#tutorial"><span class="header-section-number">7.3</span> Tutorial</a>
  <ul class="collapse">
  <li><a href="#example-data" id="toc-example-data" class="nav-link" data-scroll-target="#example-data"><span class="header-section-number">7.3.1</span> Example data</a></li>
  <li><a href="#tidyverse" id="toc-tidyverse" class="nav-link" data-scroll-target="#tidyverse"><span class="header-section-number">7.3.2</span> Tidyverse</a></li>
  <li><a href="#reading-tabular-data" id="toc-reading-tabular-data" class="nav-link" data-scroll-target="#reading-tabular-data"><span class="header-section-number">7.3.3</span> Reading tabular data</a></li>
  <li><a href="#variable-selection" id="toc-variable-selection" class="nav-link" data-scroll-target="#variable-selection"><span class="header-section-number">7.3.4</span> Variable selection</a></li>
  <li><a href="#time-objects" id="toc-time-objects" class="nav-link" data-scroll-target="#time-objects"><span class="header-section-number">7.3.5</span> Time objects</a></li>
  <li><a href="#variable-re--definition" id="toc-variable-re--definition" class="nav-link" data-scroll-target="#variable-re--definition"><span class="header-section-number">7.3.6</span> Variable (re-) definition</a></li>
  <li><a href="#axes-of-variation" id="toc-axes-of-variation" class="nav-link" data-scroll-target="#axes-of-variation"><span class="header-section-number">7.3.7</span> Axes of variation</a></li>
  <li><a href="#tidydata" id="toc-tidydata" class="nav-link" data-scroll-target="#tidydata"><span class="header-section-number">7.3.8</span> Tidy data</a></li>
  <li><a href="#aggregating-data" id="toc-aggregating-data" class="nav-link" data-scroll-target="#aggregating-data"><span class="header-section-number">7.3.9</span> Aggregating data</a></li>
  <li><a href="#sec-datacleaning" id="toc-sec-datacleaning" class="nav-link" data-scroll-target="#sec-datacleaning"><span class="header-section-number">7.3.10</span> Data cleaning</a></li>
  <li><a href="#writing-data-to-csv" id="toc-writing-data-to-csv" class="nav-link" data-scroll-target="#writing-data-to-csv"><span class="header-section-number">7.3.11</span> Writing data to CSV</a></li>
  <li><a href="#combining-relational-data" id="toc-combining-relational-data" class="nav-link" data-scroll-target="#combining-relational-data"><span class="header-section-number">7.3.12</span> Combining relational data</a></li>
  </ul></li>
  <li><a href="#sec-extramaterialwrangling" id="toc-sec-extramaterialwrangling" class="nav-link" data-scroll-target="#sec-extramaterialwrangling"><span class="header-section-number">7.4</span> Extra material</a>
  <ul class="collapse">
  <li><a href="#functional-programming-i" id="toc-functional-programming-i" class="nav-link" data-scroll-target="#functional-programming-i"><span class="header-section-number">7.4.1</span> Functional programming I</a></li>
  <li><a href="#sec-strings" id="toc-sec-strings" class="nav-link" data-scroll-target="#sec-strings"><span class="header-section-number">7.4.2</span> Strings</a></li>
  <li><a href="#functional-programming-ii" id="toc-functional-programming-ii" class="nav-link" data-scroll-target="#functional-programming-ii"><span class="header-section-number">7.4.3</span> Functional programming II</a></li>
  </ul></li>
  <li><a href="#exerciseswrangling" id="toc-exerciseswrangling" class="nav-link" data-scroll-target="#exerciseswrangling"><span class="header-section-number">7.5</span> Exercises</a>
  <ul class="collapse">
  <li><a href="#star-wars" id="toc-star-wars" class="nav-link" data-scroll-target="#star-wars">Star wars</a></li>
  <li><a href="#aggregating" id="toc-aggregating" class="nav-link" data-scroll-target="#aggregating">Aggregating</a></li>
  <li><a href="#patterns-in-data-quality" id="toc-patterns-in-data-quality" class="nav-link" data-scroll-target="#patterns-in-data-quality">Patterns in data quality</a></li>
  </ul></li>
  <li><a href="#sec-retidy" id="toc-sec-retidy" class="nav-link" data-scroll-target="#sec-retidy"><span class="header-section-number">7.6</span> Report Exercise</a>
  <ul class="collapse">
  <li><a href="#analyzing-changes-in-soil-organic-matter-during-elevated-co_2-experiments" id="toc-analyzing-changes-in-soil-organic-matter-during-elevated-co_2-experiments" class="nav-link" data-scroll-target="#analyzing-changes-in-soil-organic-matter-during-elevated-co_2-experiments">Analyzing changes in soil organic matter during elevated CO<span class="math inline">\(_2\)</span> experiments</a></li>
  <li><a href="#deliverables-for-the-report" id="toc-deliverables-for-the-report" class="nav-link" data-scroll-target="#deliverables-for-the-report">Deliverables for the report</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-datawrangling" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Data wrangling</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Chapter lead author: Benjamin Stocker</strong></p>
<section id="learning-objectives" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="learning-objectives"><span class="header-section-number">7.1</span> Learning objectives</h2>
<p>In this chapter you will learn how to manipluate and transform data, a curcial part of the data science workflow.</p>
<p>You will learn how to:</p>
<ul>
<li>read and transform tabulated datas</li>
<li>understand the ‘tidy’ data concept</li>
<li>select variables</li>
<li>Aggregate data</li>
<li>handle bad and/or missing data</li>
</ul>
</section>
<section id="setup" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="setup"><span class="header-section-number">7.2</span> Setup</h2>
<p>In this Chapter, we will need the following libraries</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="tutorial" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="tutorial"><span class="header-section-number">7.3</span> Tutorial</h2>
<p>Exploratory data analysis - the transformation, visualization, and modelling of data - is the central part of any (geo-) data science workflow and typically takes up a majority of the time we spend on a research project. The transformation of data often turns out to be particularly (and often surprisingly) time-demanding. Therefore, it is key to master typical steps of data transformation, and to implement them in a transparent fashion and efficiently - both in terms of robustness against coding errors (“bugs”) and in terms of code execution speed.</p>
<p>We refer to data <em>wrangling</em> here to encompass the steps for preparing the data set <em>prior</em> to modelling - including, the combination of variables from different data sources, the removal of bad data, and the aggregation of data to the desired resolution or granularity (e.g., averaging over all time steps in a day, or over all replicates in a sample).</p>
<p>In contrast, <em>pre-processing</em> refers to the additional steps that are either required by the the specific machine learning algorithm used with the data (e.g., centering and scaling for K-Nearest Neighbors or Neural Networks), the gap-filling of variables, or the transformation of variables guided by the resulting improvement of the predictive power of the machine learning model. Pre-processing is part of the modelling workflow and includes all steps that apply transformations that use parameters derived from the data. We will introduce and discuss data pre-processing in <a href="supervised_ml_I.html" class="quarto-xref"><span>Chapter 10</span></a>.</p>
<section id="example-data" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="example-data"><span class="header-section-number">7.3.1</span> Example data</h3>
<p>The example data used in this chapter are parallel time series of (gaseous) CO<span class="math inline">\(_2\)</span> and water vapor exchange fluxes between the vegetation and the atmosphere, along with various meteorological variables measured in parallel. Quasi-continuous measurements of temporally changing gas exchange fluxes are obtained with the eddy covariance technique which relies on the parallel quantification of vertical wind speeds and gas concentrations.</p>
<p>The data are provided at half-hourly resolution for the site <a href="https://www.swissfluxnet.ethz.ch/index.php/sites/ch-lae-laegeren/site-info-ch-lae/">CH-Lae</a>, located on the south slope of the Lägern mountain on the Swiss Plateau at 689 m a.s.l. in a mixed forest with a distinct seasonal course of active green leaves (a substantial portion of the trees in the measured forest are deciduous). The dataset is generated and formatted following standard protocols (<a href="https://fluxnet.org//data/fluxnet2015-dataset/">FLUXNET2015</a>). For more information of the variables in the dataset, see the <a href="http://fluxnet.fluxdata.org/data/fluxnet2015-dataset/">FLUXNET2015 website</a> and <a href="https://www.nature.com/articles/s41597-020-0534-3">Pastorello et al., 2020</a> for a comprehensive documentation of variable definitions and methods.</p>
<p>For our demonstrations, the following variables are the most relevant:</p>
<ul>
<li><code>TIMESTAMP_START</code>: Hour and day of the start of the measurement period for which the respective row’s data are representative. Provided in a format of “YYYYMMDDhhmm”.</li>
<li><code>TIMESTAMP_END</code>: Hour and day of the end of the measurement period for which the respective row’s data are representative. Provided in a format of “YYYYMMDDhhmm”.</li>
<li><code>TA_*</code> (°C): Air temperature.</li>
<li><code>SW_IN_*</code> (W m<span class="math inline">\(^{-2}\)</span>): Shortwave incoming radiation</li>
<li><code>LW_IN_*</code> (W m<span class="math inline">\(^{-2}\)</span>): Longwave incoming radiation</li>
<li><code>VPD_*</code> (hPa): Vapor pressure deficit (the difference between actual and saturation water vapor pressure)</li>
<li><code>PA_*</code> (kPa): Atmospheric pressure</li>
<li><code>P_*</code> (mm): Precipitation</li>
<li><code>WS_*</code> (m <span class="math inline">\(^{-1}\)</span>): Wind speed</li>
<li><code>SWC_*</code> (%): Volumetric soil water content</li>
<li><code>GPP_*</code> (<span class="math inline">\(\mu\)</span>mol CO<span class="math inline">\(_2\)</span> m<span class="math inline">\(^{-2}\)</span> s<span class="math inline">\(^{-1}\)</span>): Gross primary production (the ecosystem-level gross CO<span class="math inline">\(_2\)</span> uptake flux driven by photosynthesis)</li>
<li><code>*_QC</code>: Quality control information for the variable <code>*</code>. Important for us: <code>NEE_*_QC</code> is the quality control information for the net ecosystem CO<span class="math inline">\(_2\)</span> exchange flux (<code>NEE_*</code>) and for GPP derived from the corresponding NEE estimate (<code>GPP_*</code>). 0 = measured, 1 = good quality gap-filled, 2 = medium, 3 = poor.</li>
</ul>
<p>Suffixes <code>_*</code> indicate that multiple estimates for respective variables are available and distinguished by different suffixes. For example, variables <code>TA_*</code> contain the same information, but are derived with slightly different assumptions and gap-filling techniques. The meanings of suffixes are described in <a href="https://www.nature.com/articles/s41597-020-0534-3">Pastorello et al., 2020</a>.</p>
</section>
<section id="tidyverse" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="tidyverse"><span class="header-section-number">7.3.2</span> Tidyverse</h3>
<p>The tidyverse is a collection of R packages and functions that share a common design philosophy, enabling a particularly efficient implementation of transformation steps on tabular data. The most important data and function design principle of the tidyverse is that each function takes a data frame as its first argument and returns a data frame as its output.</p>
<!-- Working on a (geo-) data science project, we want to efficiently progress through the multiple circles of exploratory data analysis. The following aspects are particularly important for fast and error-free progression. First, the programming language should be conducive of fast, intuitive, and error-free coding. Second, code that we have written once should be legible by others and by our future selves (even after a long holiday or after the manuscript has been seen by all reviewers months after we finished the analysis for our initial submission). It's the daily reality of us (geo-) data scientist that the code we write is harder to read than text in a newspaper, and that it will have bugs. There is (so far) no magic solution to this. But the R tidyverse comes close.  -->
<p>From this design principles, even the most convoluted code and implementation of data transformation steps fall into place and fast and error-free progression through exploratory data analysis is facilitated. Therefore, you will be introduced to the R {tidyverse} here and we heavily rely on this <em>dialect</em> of the R language throughout the remainder of this course.</p>
</section>
<section id="reading-tabular-data" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="reading-tabular-data"><span class="header-section-number">7.3.3</span> Reading tabular data</h3>
<p>Tabular data are organised in rows and columns. R data frames are tabular data. As introduced in <a href="primers.html" class="quarto-xref"><span>Chapter 2</span></a>, each column can be regarded as a vector of a certain type. Each row contains the same number of columns and each column contains the same type of values (for example numeric, or characters). Each row can be regarded as a separate instance or data record - for example a record of simultaneously taken measurements of different variables, along with some attributes and meta information (e.g., the date). In <a href="data_variety.html" class="quarto-xref"><span>Chapter 6</span></a>, you will be introduced to other types of data.</p>
<p>The most common format for tabular data are CSV (comma-separated-values), typically indicated by the file name suffix <code>.csv</code>. CSV is a text-based file format, readable across platforms and does not rely on proprietary software (as opposed to, for example, <code>.xlsx</code>). The first row in a CSV file typically specifies the name of the variable provided in the respective column.</p>
<p>Let’s get started with working with our example data set and read it into R, as the variable <code>half_hourly_fluxes</code>. Note that the naming of variables can be important for keeping code legible. Chose intuitively understandable names that describe what the object represents (as done here).</p>
<p>To import the data into the R environment, we use the function <code>read_csv()</code> from the {readr} package (part of tidyverse). In other R code, you will also encounter the base R <code>read.csv()</code> function. However, <code>read_csv()</code> is much faster and reads data into a tidyverse-data frame (a <em>tibble</em>) which has some useful additional characteristics, on top of a common R data frame. For example, <em>tibbles</em> generate a nicely readable output when printing the object as is done below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"./data/FLX_CH-Lae_FLUXNET2015_FULLSET_HH_2004-2006.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 52,608 × 235
   TIMESTAMP_START TIMESTAMP_END TA_F_MDS TA_F_MDS_QC TA_ERA  TA_F TA_F_QC
             &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
 1    200401010000  200401010030    -9999       -9999  -2.22 -2.22       2
 2    200401010030  200401010100    -9999       -9999  -2.25 -2.25       2
 3    200401010100  200401010130    -9999       -9999  -2.28 -2.28       2
 4    200401010130  200401010200    -9999       -9999  -2.50 -2.50       2
 5    200401010200  200401010230    -9999       -9999  -2.72 -2.72       2
 6    200401010230  200401010300    -9999       -9999  -2.94 -2.94       2
 7    200401010300  200401010330    -9999       -9999  -3.17 -3.17       2
 8    200401010330  200401010400    -9999       -9999  -3.39 -3.39       2
 9    200401010400  200401010430    -9999       -9999  -3.61 -3.61       2
10    200401010430  200401010500    -9999       -9999  -3.59 -3.59       2
# ℹ 52,598 more rows
# ℹ 228 more variables: SW_IN_POT &lt;dbl&gt;, SW_IN_F_MDS &lt;dbl&gt;,
#   SW_IN_F_MDS_QC &lt;dbl&gt;, SW_IN_ERA &lt;dbl&gt;, SW_IN_F &lt;dbl&gt;, SW_IN_F_QC &lt;dbl&gt;,
#   LW_IN_F_MDS &lt;dbl&gt;, LW_IN_F_MDS_QC &lt;dbl&gt;, LW_IN_ERA &lt;dbl&gt;, LW_IN_F &lt;dbl&gt;,
#   LW_IN_F_QC &lt;dbl&gt;, LW_IN_JSB &lt;dbl&gt;, LW_IN_JSB_QC &lt;dbl&gt;, LW_IN_JSB_ERA &lt;dbl&gt;,
#   LW_IN_JSB_F &lt;dbl&gt;, LW_IN_JSB_F_QC &lt;dbl&gt;, VPD_F_MDS &lt;dbl&gt;,
#   VPD_F_MDS_QC &lt;dbl&gt;, VPD_ERA &lt;dbl&gt;, VPD_F &lt;dbl&gt;, VPD_F_QC &lt;dbl&gt;, PA &lt;dbl&gt;, …</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>To reproduce this code chunk, you can download the file <code>FLX_CH-Lae_FLUXNET2015_FULLSET_HH_2004-2006.csv</code> from <a href="https://raw.githubusercontent.com/geco-bern/agds_book/refs/heads/main/book/data/FLX_CH-Lae_FLUXNET2015_FULLSET_HH_2004-2006.csv">here</a> and read it from the local path where the file is stored on your machine. All data files used in this tutorials are stored <a href="https://github.com/geco-bern/agds_book/tree/main/book/data">here</a>.</p>
</blockquote>
<p>Since the file is properly formatted, with variable names given in the first line of the file, the function <code>read_csv()</code> identifies them correctly as column names and interprets values in each column as values of a consistent type (as numeric <code>&lt;dbl&gt;</code>). The file is also automatically machine-readable because it has no merged cells and only one value per cell.</p>
</section>
<section id="variable-selection" class="level3" data-number="7.3.4">
<h3 data-number="7.3.4" class="anchored" data-anchor-id="variable-selection"><span class="header-section-number">7.3.4</span> Variable selection</h3>
<p>For our further data exploration, we will reduce the data frame we are working with and select a reduced set of variables. Reducing the dataset can have the advantage of speeding up further processing steps, especially when the data are large. For the further steps in this chapter we will now subset our original data. We select the following variants of variables described above, plus some additional variables (further information in <a href="https://www.nature.com/articles/s41597-020-0534-3">Pastorello et al., 2020</a>):</p>
<ul>
<li>All variables with names starting with <code>TIMESTAMP</code>)</li>
<li>All meteorological variables derived following the “final gap-filled method”, as indicated with names ending with <code>_F</code>.</li>
<li>GPP estimates that are based on the nighttime decomposition method, using the “most representative” of different gap-filling versions, after having applied the variable u-star filtering method (<code>GPP_NT_VUT_REF</code>) and the corresponding quality control information (<code>NEE_VUT_REF_QC</code>)</li>
<li>Soil water measured at different depths (variables starting with <code>SWC_F_MDS_</code>)</li>
<li>Do not use any radiation variables derived with the “JSBACH” algorithm (not with a name that contains the string <code>JSB</code>)</li>
<li>Flag indicating whether a time step is at night (<code>NIGHT</code>)</li>
</ul>
<p>This is implemented by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="ot">&lt;-</span> <span class="fu">select</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  half_hourly_fluxes,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">starts_with</span>(<span class="st">"TIMESTAMP"</span>),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ends_with</span>(<span class="st">"_F"</span>),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  GPP_NT_VUT_REF,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  NEE_VUT_REF_QC,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">starts_with</span>(<span class="st">"SWC_F_MDS_"</span>),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="fu">contains</span>(<span class="st">"JSB"</span>),</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  NIGHT</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This reduces our dataset from 235 available variables to 20 variables. As you can see, <code>select()</code> is a powerful tool to apply multiple selection criteria on your data frame in one step. It takes many functions that make filtering the columns easier. For example, criteria can be formulated based on the variable names with <code>starts_with()</code>, <code>ends_with()</code>, <code>contains()</code>, <code>matches()</code>, etc. Using these functions within <code>select()</code> can help if several column names start with the same characters or contain the same pattern and all need to be selected. If a minus (<code>-</code>) is added in front of a column name or one of the mentioned functions within <code>select()</code>, then R will not include the stated column(s). Note that the selection criteria are evaluated in the order we write them in the <code>select()</code> function call. You can find the complete reference for selecting variables <a href="https://dplyr.tidyverse.org/reference/select.html">here</a>.</p>
</section>
<section id="time-objects" class="level3" data-number="7.3.5">
<h3 data-number="7.3.5" class="anchored" data-anchor-id="time-objects"><span class="header-section-number">7.3.5</span> Time objects</h3>
<p>The automatic interpretation of the variables <code>TIMESTAMP_START</code> and <code>TIMESTAMP_END</code> by the function <code>read_csv()</code> is not optimal:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(half_hourly_fluxes<span class="sc">$</span>TIMESTAMP_START[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.character</span>(half_hourly_fluxes<span class="sc">$</span>TIMESTAMP_START[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "200401010000"</code></pre>
</div>
</div>
<p>As we can see, it is considered by R as a numeric variable with 12 digits (“double-precision”, occupying 64 bits in computer memory). After printing the variable as a string, we can guess that the format is: <code>YYYYMMDDhhmm</code>. The {lubridate} package is designed to facilitate processing date and time objects. Knowing the format of the timestamp variables in our dataset, we can use <code>ymd_hm()</code> to convert them to actual date-time objects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dates <span class="ot">&lt;-</span> <span class="fu">ymd_hm</span>(half_hourly_fluxes<span class="sc">$</span>TIMESTAMP_START)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>dates[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2004-01-01 UTC"</code></pre>
</div>
</div>
<p>Working with such date-time objects facilitates typical operations on time series. For example, adding one day can be done by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>nextday <span class="ot">&lt;-</span> dates <span class="sc">+</span> <span class="fu">days</span>(<span class="dv">1</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>nextday[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2004-01-02 UTC"</code></pre>
</div>
</div>
<p>The following returns the month of each date object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">month</span>(dates[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>The number 1 stands for the month of the year, i.e., January. You can find more information on formatting dates and time within the {tidyverse} <a href="https://r4ds.had.co.nz/dates-and-times.html">here</a>, and a complete reference of the {lubridate} package is available <a href="https://lubridate.tidyverse.org/">here</a>.</p>
</section>
<section id="variable-re--definition" class="level3" data-number="7.3.6">
<h3 data-number="7.3.6" class="anchored" data-anchor-id="variable-re--definition"><span class="header-section-number">7.3.6</span> Variable (re-) definition</h3>
<p>Since <code>read_csv()</code> did not interpret the <code>TIMESTAMP_*</code> variables as desired, we may convert the entire column in the data frame into a date-time object. In base-R, we would do this by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes<span class="sc">$</span>TIMESTAMP_START <span class="ot">&lt;-</span> <span class="fu">ymd_hm</span>(half_hourly_fluxes<span class="sc">$</span>TIMESTAMP_START)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Modifying existing or creating new variables (columns) in a data frame is done in the {tidyverse} using the function <code>mutate()</code>. The equivalent statement is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="ot">&lt;-</span> <span class="fu">mutate</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  half_hourly_fluxes,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">TIMESTAMP_START =</span> <span class="fu">ymd_hm</span>(TIMESTAMP_START)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Note: Avoid using whitespaces (‘Leerzeichen’) to name columns in a dataframe because it can cause troubles down the line. Instead, use <code>_</code> to separate words in one name.</p>
</blockquote>
<p>In the code chunk above, the function <code>mutate()</code> is from the tidyverse package {dplyr}. It takes a dataframe as its first argument (here <code>half_hourly_fluxes</code>) and returns a dataframe as its output. You will encounter an alternative, but equivalent, syntax in the following form:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="ot">&lt;-</span> half_hourly_fluxes <span class="sc">|&gt;</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">TIMESTAMP_START =</span> <span class="fu">ymd_hm</span>(TIMESTAMP_START))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here, the <strong>pipe</strong> operator <code>|&gt;</code> is used. It “pipes” the object evaluated on its left side into the function on its right side, where the object takes the place of (but is not spelled out as) the <em>first argument</em> of that function. Using the pipe operator can have the advantage of facilitating the separation, removal, inserting, or re-arranging of individual transformation steps. Arguably, it facilitates reading code, especially for complex data transformation workflows. Therefore, you will encounter the pipe operator frequently throughout the remainder of this course.</p>
<blockquote class="blockquote">
<p>Note: The pipe operator is so popular that has been recently included in the latest versions of base R (version 4.1.0 and beyond). This is the <code>|&gt;</code> pipe we just introduced. Nevertheless, you may encounter the <code>%&gt;%</code> operator, which is the original pipe from the {magrittr} package (part of the {tidyverse}).</p>
</blockquote>
<blockquote class="blockquote">
<p>Note: If you cannot update R and have a version older than 4.1.0, just use the <code>magrittr</code> pipe <code>%&gt;%</code> throughout. This can happen if you have an older Macbook that can’t operate the latest Operating System version.</p>
</blockquote>
<p>Mutating both our timestamp variables could be written as <code>mutate(TIMESTAMP_START = ymd_hm(TIMESTAMP_START), TIMESTAMP_END = ymd_hm(TIMESTAMP_END))</code>. Sometimes, such multiple-variable mutate statements can get quite long. A handy short version of this can be implemented using <code>across()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="ot">&lt;-</span> half_hourly_fluxes <span class="sc">|&gt;</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"TIMESTAMP_"</span>), ymd_hm))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will encounter more ways to use mutate later in this tutorial. A complete reference to <code>mutate()</code> is available <a href="https://r4ds.had.co.nz/transform.html#add-new-variables-with-mutate">here</a>.</p>
<p>If you only want to change the name of a variable, but not modify its values, you can do so with the {dplyr} function <code>rename()</code>.</p>
</section>
<section id="axes-of-variation" class="level3" data-number="7.3.7">
<h3 data-number="7.3.7" class="anchored" data-anchor-id="axes-of-variation"><span class="header-section-number">7.3.7</span> Axes of variation</h3>
<p>Tabular data are two-dimensional (rows <span class="math inline">\(\times\)</span> columns), but not all two-dimensional data are tabular. For example, raster data are a two-dimensional array of data (a matrix) representing variables on an evenly spaced grid, for example pixels in remotely sensed imagery. For example the <code>volcano</code> data (provided as an example dataset in R) is a matrix - each column contains the same variable, and no variable names are provided.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>volcano[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3] [,4] [,5]
[1,]  100  100  101  101  101
[2,]  101  101  102  102  102
[3,]  102  102  103  103  103
[4,]  103  103  104  104  104
[5,]  104  104  105  105  105</code></pre>
</div>
</div>
<p>In the <code>volcano</code> dataset, rows and columns represent different geographic positions in latitude and longitude, respectively. The <code>volcano</code> data are not tabular data. Another typical example for non-tabular data are climate model outputs. They are typically given as <em>arrays</em> with more than two dimensions. Typically, this is longitude, latitude, and time, and sometimes a vertical dimension representing, for example, elevation. Such data are multi-dimensional and, as such, not tabular.</p>
<p>Tabular data, although formatted in two dimensions by rows and columns, may represent data that varies along multiple axes. Most environmental data are <em>structured</em>, that is, values of “nearby” observations tend to be more similar than values of “distant” observations. Here, “nearby” and “distant” may refer to a spatial distance, but not necessarily so. Structure in data arises from similarity of the subjects generating the data (e.g., evapotranspiration over two croplands may be more similar than evapotranspiration over a forest), or from temporal proximity. In biological data, there may be a genetic structure arising from evolutionary relatedness (<a href="https://onlinelibrary.wiley.com/doi/10.1111/ecog.02881">Roberts et al., 2016</a>). Note also that temporal proximity is more complex than than being governed by a single dimension - time. In environmental data, time is often expressed through periodically varying conditions (the diurnal and seasonal cycles). It’s often critical to understand and account for the structure in data when analysing it and using it for model fitting. Challenges are posed when structure is not apparent or not known.</p>
<p>Note also that some structures are <em>hierarchical</em>. For example, data may be structured by postal codes within cantons; or by hours within a day within a year. Biological data may be generated by species within <em>genera</em> within <em>families</em>. Data from experiments is typically structured as <em>samples</em> within <em>treatments</em>. You see, structure in data is rather the rule than the exception.</p>
<p>Our example data contains values recorded at each half-hourly time interval over the course of eleven years (check by <code>nrow(half_hourly_fluxes)/(2*24*365)</code>). The data are recorded at a site, located in the temperate climate zone, where solar radiation and therefore also other meteorological variables and ecosystem fluxes vary substantially over the course of a day and over the course of a year. Although not explicitly separated, the date-time object thus encodes information along multiple <em>axes of variation</em> in the data. For example, over the course of one day (<code>2*24</code> rows in our data), the shortwave incoming radiation <code>SW_IN_F</code> varies over a typical diurnal cycle:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  half_hourly_fluxes[<span class="dv">1</span><span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span><span class="dv">24</span>),]<span class="sc">$</span>TIMESTAMP_START,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  half_hourly_fluxes[<span class="dv">1</span><span class="sc">:</span>(<span class="dv">2</span><span class="sc">*</span><span class="dv">24</span>),]<span class="sc">$</span>SW_IN_F,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"l"</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data_wrangling_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Note: <code>plot()</code> is the very basic of plotting data. In <a href="data_vis.html" class="quarto-xref"><span>Chapter 8</span></a>, you will get introduced to additional methods for visualising data. The argument <code>type = "l"</code> indicates that we want a line plot, rather than points.</p>
</blockquote>
<p>Over the course of an entire year, shortwave incoming radiation varies with the seasons, peaking in summer:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  half_hourly_fluxes[<span class="dv">1</span><span class="sc">:</span>(<span class="dv">365</span><span class="sc">*</span><span class="dv">2</span><span class="sc">*</span><span class="dv">24</span>),]<span class="sc">$</span>TIMESTAMP_START,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  half_hourly_fluxes[<span class="dv">1</span><span class="sc">:</span>(<span class="dv">365</span><span class="sc">*</span><span class="dv">2</span><span class="sc">*</span><span class="dv">24</span>),]<span class="sc">$</span>SW_IN_F,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"l"</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data_wrangling_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>All data frames have two dimensions, rows and columns. Our data frame is organised along half-hourly time steps in rows. As described above, these time steps belong to different days, months, and years, although these “axes of variation” are not reflected by the structure of the data frame object itself and we do not have columns that indicate the day, month or year of each half-hourly time step. This would be redundant information since the date-time objects of columns <code>TIMESTAMP_*</code> contain this information. However, for certain applications, it may be useful to separate information regarding these axes of variation more explicitly. For example by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">year</span>(TIMESTAMP_START),</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">month =</span> <span class="fu">month</span>(TIMESTAMP_START),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">doy =</span> <span class="fu">yday</span>(TIMESTAMP_START)     <span class="co"># day of year</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">|&gt;</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(TIMESTAMP_START, TIMESTAMP_END, year, month, doy)  <span class="co"># for displaying</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 52,608 × 5
   TIMESTAMP_START     TIMESTAMP_END        year month   doy
   &lt;dttm&gt;              &lt;dttm&gt;              &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 2004-01-01 00:00:00 2004-01-01 00:30:00  2004     1     1
 2 2004-01-01 00:30:00 2004-01-01 01:00:00  2004     1     1
 3 2004-01-01 01:00:00 2004-01-01 01:30:00  2004     1     1
 4 2004-01-01 01:30:00 2004-01-01 02:00:00  2004     1     1
 5 2004-01-01 02:00:00 2004-01-01 02:30:00  2004     1     1
 6 2004-01-01 02:30:00 2004-01-01 03:00:00  2004     1     1
 7 2004-01-01 03:00:00 2004-01-01 03:30:00  2004     1     1
 8 2004-01-01 03:30:00 2004-01-01 04:00:00  2004     1     1
 9 2004-01-01 04:00:00 2004-01-01 04:30:00  2004     1     1
10 2004-01-01 04:30:00 2004-01-01 05:00:00  2004     1     1
# ℹ 52,598 more rows</code></pre>
</div>
</div>
<p>Note that we used <code>mutate()</code> here to create a new variable (column) in the data frame, as opposed to above where we overwrote an existing variable with the same function.</p>
</section>
<section id="tidydata" class="level3" data-number="7.3.8">
<h3 data-number="7.3.8" class="anchored" data-anchor-id="tidydata"><span class="header-section-number">7.3.8</span> Tidy data</h3>
<p>Data comes in many forms and shapes. For example, Excel provides a playground for even the wildest layouts of information in some remotely tabular form and merged cells as we will see in the <a href="#exerciseswrangling">Exercises</a>. A data frame imposes a relatively strict formatting in named columns of equal length. But even data frames can come in various shapes - even if the information they contain is the same.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>co2_concentration</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 36 × 3
    year month co2_concentration
   &lt;int&gt; &lt;ord&gt;             &lt;dbl&gt;
 1  1959 Jan                315.
 2  1959 Feb                316.
 3  1959 Mar                316.
 4  1959 Apr                318.
 5  1959 May                318.
 6  1959 Jun                318 
 7  1959 Jul                316.
 8  1959 Aug                315.
 9  1959 Sep                314.
10  1959 Oct                313.
# ℹ 26 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>co2_concentration_monthly</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 13
   year   Jan   Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct   Nov   Dec
  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  1959  315.  316.  316.  318.  318.  318   316.  315.  314.  313.  315.  315.
2  1960  316.  317.  317.  319.  320.  319.  318.  316.  314   314.  315.  316.
3  1961  317.  318.  318.  319.  320.  320.  318.  317.  315.  315.  316.  317.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>co2_concentration_yearly</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 4
   month `1959` `1960` `1961`
   &lt;ord&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 Jan     315.   316.   317.
 2 Feb     316.   317.   318.
 3 Mar     316.   317.   318.
 4 Apr     318.   319.   319.
 5 May     318.   320.   320.
 6 Jun     318    319.   320.
 7 Jul     316.   318.   318.
 8 Aug     315.   316.   317.
 9 Sep     314.   314    315.
10 Oct     313.   314.   315.
11 Nov     315.   315.   316.
12 Dec     315.   316.   317.</code></pre>
</div>
</div>
<p>There are advantages for interoperability and ease of use when data frames come with consistent layouts, adhering to certain design principles. We have learned that in tabular data, each row contains the same number of columns and each column contains the same type of values (for example numeric, or characters). And that each row can be regarded as a separate instance of the same type, for example a record of simultaneously taken measurements, along with some attributes. Following these principles strictly leads to <em>tidy data</em>. In essence, quoting <a href="https://r4ds.had.co.nz/tidy-data.html">Wickham and Grolemund (2017)</a>, data are tidy if:</p>
<ul>
<li>Each variable has its own column.</li>
<li>Each observation has its own row.</li>
<li>Each value has its own cell.</li>
</ul>
<div id="fig-tidy" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig.align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tidy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./figures/tidy_data.png" class="img-fluid figure-img" style="width:100.0%" data-fig.align="center">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tidy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: Rules for tidy data. Figure from <a href="https://r4ds.had.co.nz/tidy-data.html">Wickham and Grolemund (2017)</a>.
</figcaption>
</figure>
</div>
<p>The {tidyr} package provides powerful functions to make data tidy. In the examples above, <code>co2_concentration_monthly</code> and and <code>co2_concentration_yearly</code> are not tidy. In <code>co2_concentration_monthly</code>, the same variable (CO2 concentration) appears in multiple columns. Organising columns by months leads to a “wide” table format. We can convert it to a “long” format by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>co2_concentration_monthly <span class="sc">|&gt;</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">13</span>, <span class="at">names_to =</span> <span class="st">"month"</span>, <span class="at">values_to =</span> <span class="st">"co2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 36 × 3
    year month   co2
   &lt;int&gt; &lt;chr&gt; &lt;dbl&gt;
 1  1959 Jan    315.
 2  1959 Feb    316.
 3  1959 Mar    316.
 4  1959 Apr    318.
 5  1959 May    318.
 6  1959 Jun    318 
 7  1959 Jul    316.
 8  1959 Aug    315.
 9  1959 Sep    314.
10  1959 Oct    313.
# ℹ 26 more rows</code></pre>
</div>
</div>
<p>This corresponds to the format of <code>co2_concentration</code> and is tidy. A long format of data frames is required to visualise data using the plotting functions of the {ggplot2} package which will be introduced in <a href="data_vis.html" class="quarto-xref"><span>Chapter 8</span></a>.</p>
<p>Either way, for certain applications, it may be advantageous to work with a wide format. We can convert from a long to a wide format by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>co2_concentration <span class="sc">|&gt;</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> year, <span class="at">values_from =</span> co2_concentration)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 4
   month `1959` `1960` `1961`
   &lt;ord&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 Jan     315.   316.   317.
 2 Feb     316.   317.   318.
 3 Mar     316.   317.   318.
 4 Apr     318.   319.   319.
 5 May     318.   320.   320.
 6 Jun     318    319.   320.
 7 Jul     316.   318.   318.
 8 Aug     315.   316.   317.
 9 Sep     314.   314    315.
10 Oct     313.   314.   315.
11 Nov     315.   315.   316.
12 Dec     315.   316.   317.</code></pre>
</div>
</div>
<p>When seeking, for example, the average CO2 concentration for each month, you may be tempted to work with a wide data frame and treat it as a matrix to calculate a mean by rows. You can do so, but then, you leave the <code>tidyverse</code>. This will complicate your life. You’ll learn how to perform tidy data aggregation below.</p>
<p>The concept of tidy data can even be taken further by understanding a “value” as any object type, e.g., a list or a data frame. This leads to a list or data frame “nested” within a data frame. You will learn more about this below.</p>
</section>
<section id="aggregating-data" class="level3" data-number="7.3.9">
<h3 data-number="7.3.9" class="anchored" data-anchor-id="aggregating-data"><span class="header-section-number">7.3.9</span> Aggregating data</h3>
<p>Aggregating data refers to collapsing a larger set of values into a smaller set of values that are derived from the larger set. For example, we can aggregate over all <span class="math inline">\(N\)</span> rows in a data frame (<span class="math inline">\(N\times M\)</span>), calculating the sum for each of the <span class="math inline">\(M\)</span> columns. This returns a data frame (<span class="math inline">\(1 \times M\)</span>) with the same number of columns as the initial data frame, but only one row. Often, aggregations are done not across all rows but for rows within <span class="math inline">\(G\)</span> groups of rows. This yields a data frame (<span class="math inline">\(G \times M\)</span>) with the number of rows corresponding to the number of groups.</p>
<p>Let’s say we want to calculate the mean of half-hourly shortwave radiation within each day. We thus have <span class="math inline">\(N\)</span> half-hourly time steps in <span class="math inline">\(G\)</span> days. That is, to aggregate our half-hourly data to daily data by taking a mean. There are two pieces of information needed for an aggregation step: The factor (or “axis of variation”), here days, that groups a vector of values for collapsing it into a single value, and the function used for collapsing values, here, the <code>mean()</code> function. This function should take a vector as an argument and return a single value as an output. These two steps are implemented by the {dplyr} functions <code>group_by()</code> and <code>summarise()</code>. The entire aggregation workflow is implemented by the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>daily_fluxes <span class="ot">&lt;-</span> half_hourly_fluxes <span class="sc">|&gt;</span>  </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as_date</span>(TIMESTAMP_START)) <span class="sc">|&gt;</span>  <span class="co"># converts the ymd_hm-formatted date-time object to a date-only object (ymd)</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(date) <span class="sc">|&gt;</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">SW_IN_F =</span> <span class="fu">mean</span>(SW_IN_F))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The seasonal course can now be more clearly be visualized with the data aggregated to daily values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(daily_fluxes[<span class="dv">1</span><span class="sc">:</span><span class="dv">365</span>,]<span class="sc">$</span>date, daily_fluxes[<span class="dv">1</span><span class="sc">:</span><span class="dv">365</span>,]<span class="sc">$</span>SW_IN_F, <span class="at">type =</span> <span class="st">"l"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data_wrangling_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can also apply multiple aggregation functions to different variables simultaneously. In the example below, we aggregate half-hourly data to daily data by…</p>
<ul>
<li><p>taking the daily mean GPP</p></li>
<li><p>counting the number of half-hourly data points by day</p></li>
<li><p>counting the number of measured (not gap-filled) data points</p></li>
<li><p>taking the mean shortwave radiation</p></li>
</ul>
<p>Finally, we calculate the fraction of measured underlying half-hourly data from which the aggregation is calculated and we save the daily data frame as a CSV file for later use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>daily_fluxes <span class="ot">&lt;-</span> half_hourly_fluxes <span class="sc">|&gt;</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as_date</span>(TIMESTAMP_START)) <span class="sc">|&gt;</span>   <span class="co"># converts time object to a date object</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(date) <span class="sc">|&gt;</span> </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">GPP_NT_VUT_REF =</span> <span class="fu">mean</span>(GPP_NT_VUT_REF, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">n_datapoints =</span> <span class="fu">n</span>(), <span class="co"># counts the number of observations per day</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">n_measured =</span> <span class="fu">sum</span>(NEE_VUT_REF_QC <span class="sc">==</span> <span class="dv">0</span>), <span class="co"># counts the number of actually measured data (excluding gap-filled and poor quality data)</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">SW_IN_F =</span> <span class="fu">mean</span>(SW_IN_F, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),  <span class="co"># we will use this later</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">.groups =</span> <span class="st">'drop'</span> <span class="co"># to un-group the resulting data frame</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>              ) <span class="sc">|&gt;</span> </span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">f_measured =</span> n_measured <span class="sc">/</span> n_datapoints) <span class="co"># calculate the fraction of measured values over total observations</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(daily_fluxes, <span class="at">file =</span> <span class="st">"data/daily_fluxes.csv"</span>)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>daily_fluxes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,096 × 6
   date       GPP_NT_VUT_REF n_datapoints n_measured SW_IN_F f_measured
   &lt;date&gt;              &lt;dbl&gt;        &lt;int&gt;      &lt;int&gt;   &lt;dbl&gt;      &lt;dbl&gt;
 1 2004-01-01        -0.0138           48          0    38.1          0
 2 2004-01-02         0.768            48          0    23.9          0
 3 2004-01-03         0.673            48          0    54.1          0
 4 2004-01-04        -0.322            48          0    41.7          0
 5 2004-01-05         0.841            48          0    17.4          0
 6 2004-01-06         1.22             48          0    40.5          0
 7 2004-01-07         0.215            48          0    31.6          0
 8 2004-01-08         1.11             48          0    58.4          0
 9 2004-01-09         1.44             48          0    11.9          0
10 2004-01-10         0.364            48          0    27.6          0
# ℹ 1,086 more rows</code></pre>
</div>
</div>
<p>Note that above, we specified the argument <code>.groups = 'drop'</code> to “un-group” the resulting data frame. The same can also be achieved by a separate function call <code>ungroup()</code> after the <code>summarise()</code> step.</p>
<p>More info on how to group values using summarise functions <a href="https://r4ds.had.co.nz/transform.html#grouped-summaries-with-summarise">here</a>, or a summary on the inputs the function <a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a> and <a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a> take.</p>
<p>Aggregating is related to <em>nesting</em> performed by the {tidyr} function <code>nest()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="sc">|&gt;</span>  </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as_date</span>(TIMESTAMP_START)) <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(date) <span class="sc">|&gt;</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,096 × 2
# Groups:   date [1,096]
   date       data              
   &lt;date&gt;     &lt;list&gt;            
 1 2004-01-01 &lt;tibble [48 × 20]&gt;
 2 2004-01-02 &lt;tibble [48 × 20]&gt;
 3 2004-01-03 &lt;tibble [48 × 20]&gt;
 4 2004-01-04 &lt;tibble [48 × 20]&gt;
 5 2004-01-05 &lt;tibble [48 × 20]&gt;
 6 2004-01-06 &lt;tibble [48 × 20]&gt;
 7 2004-01-07 &lt;tibble [48 × 20]&gt;
 8 2004-01-08 &lt;tibble [48 × 20]&gt;
 9 2004-01-09 &lt;tibble [48 × 20]&gt;
10 2004-01-10 &lt;tibble [48 × 20]&gt;
# ℹ 1,086 more rows</code></pre>
</div>
</div>
<p>Here, the data frame has one row per date and therefore the same number of rows as the data frame <code>daily_fluxes</code>, but the data itself is not reduced by a summarising function. Instead, the data are kept at the half-hourly level, but it’s nested inside the new column <code>data</code>, which now contains a list of half-hourly data frames for each day. This is just a brief perspective of what nesting is about. More is explained in Section <a href="#sec-extramaterialwrangling" class="quarto-xref"><span>Section 7.4</span></a>. More comprehensive tutorials on nesting and functional programming are provided in <a href="https://dcl-prog.stanford.edu/">Altman, Behrman and Wickham (2021)</a> or in <a href="https://r4ds.had.co.nz/iteration.html">Wickham and Grolemund (2017), Chapter 21</a>.</p>
</section>
<section id="sec-datacleaning" class="level3" data-number="7.3.10">
<h3 data-number="7.3.10" class="anchored" data-anchor-id="sec-datacleaning"><span class="header-section-number">7.3.10</span> Data cleaning</h3>
<p>Data cleaning is often a time-consuming task and decisions taken during data cleaning may be critical for analyses and modelling. In the following, we distinguish between cleaning formats, the identification (and removal) of “bad” data, and the gap-filling of missing or removed data. An excellent resource for further reading is the <a href="https://github.com/Quartz/bad-data-guide">Quartz Guide to Bad Data</a> which provides an overview of how to deal with different types of bad data.</p>
<section id="cleaning-formats" class="level4" data-number="7.3.10.1">
<h4 data-number="7.3.10.1" class="anchored" data-anchor-id="cleaning-formats"><span class="header-section-number">7.3.10.1</span> Cleaning formats</h4>
<p>As a general principle, we want to have <em>machine readable</em> data. Key for achieving machine-readability is that a cell should only contain one value of one type. Hence, for example, character strings should be kept in separate columns (as separate variables) from numeric data. Character strings can impose particular challenges for achieving machine-readability. Typically, they encode categorical or ordinal information, but are prone to spelling inconsistencies or errors that undermine the ordering or categorization. Here are typical examples for challenges working with character strings and lessons for avoiding problems:</p>
<ul>
<li><p>Often, character strings encode the units of a measurement, and entries may be <code>c("kg m-2", "kg/m2", "Kg / m2", "1000 g m-2")</code> . They are all equivalent, but “the machine” treats them as non-identical. To clean such data, one may compile a lookup-table to identify equivalent (but not identical) strings. Much better is to specify a consistent treatment of units before data collection.</p></li>
<li><p>Even if the data are clean and contain a consistently spelled categorical variable in the form of a character string, R doesn’t necessarily treat it as categorical. For certain downstream steps of the workflow, it may be necessary to transform such a variable to one of type <code>factor</code>. For example, as entries of an unordered categorical variable, we have <code>unique(df$gender) = c("female", "male", "non-binary")</code>. To treat them as categorical and not just mere character strings, we would have to do:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">gender =</span> <span class="fu">as.factor</span>(gender))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Character strings may encode ordinal information. For example, entries specify quality control information and are one of <code>c("good quality", "fair quality, "poor quality")</code>. A challenge could be that the spelling is inconsistent (<code>c("Good quality", "good quality", …)</code>). Using integers (positive natural numbers) instead of character strings avoids such challenges and enforces an order. The quality control variable <code>NEE_VUT_REF_QC</code> in our example dataset <code>half_hourly_fluxes</code> follows this approach:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(half_hourly_fluxes<span class="sc">$</span>NEE_VUT_REF_QC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3 2 1 0</code></pre>
</div>
</div>
<ul>
<li>An entry like <code>&gt;10 m</code> is not a friend of a data scientist. Here, we have three pieces of information: <code>&gt;</code> as in “greater than”, <code>10</code>, and <code>m</code> indicating the units. A machine-readable format would be obtained by creating separate columns for each piece of information. The <code>&gt;</code> should be avoided already at the stage of recording the data. Here, we may have to find a solution for encoding it in a machine readable manner (see <a href="#exerciseswrangling">Exercises</a>).</li>
</ul>
<!-- -   Can you think of more such examples? (-\> Exercises)  -->
<p>String manipulations are usually required for cleaning data. The <a href="#sec-strings" class="quarto-xref"><span>Section 7.4.2</span></a> below demonstrates some simple examples.</p>
<p>Note that a majority of machine learning algorithms and other statistical model types require all data to be numeric. Methods exist to convert categorical data into numeric data, as we will learn later. We re-visit data cleaning in the form of data <em>pre-processing</em> as part of the modelling workflow in <a href="supervised_ml_I.html" class="quarto-xref"><span>Chapter 10</span></a>.</p>
</section>
<section id="sec-baddata" class="level4" data-number="7.3.10.2">
<h4 data-number="7.3.10.2" class="anchored" data-anchor-id="sec-baddata"><span class="header-section-number">7.3.10.2</span> Bad data</h4>
<p>Data may be “bad” for different reasons, including sensor error, human error, a data point representing a different population, or unsuitable measurement conditions. In this sense, data are “bad” if they don’t represent what they are assumed by the user to represent. Its presence in analyses and modelling may undermine the model skill or even lead to spurious results. A goal of data cleaning typically is to remove bad data. But how to detect them? And how safe is it to remove them?</p>
<p>A diversity of processes may generate bad data and it is often not possible to formulate rules and criteria for their identification <em>a priori</em>. Therefore, an understanding of the data and the data generation processes is important for the identification and treatment of bad data. Often, such an understanding is gained by repeated exploratory data analysis cycles, involving the visualization, transformation, and analysis of the data.</p>
<p>Ideally, information about the quality of the data are provided as part of the dataset. Also other meta-information (e.g., sensor type, human recording the data, environmental conditions during the data collection) may be valuable for data cleaning purposes. In our example dataset, the column with suffices <code>_QC</code> provide such information (see ‘Example data’ section above) and an example for their use in data cleaning is given further below.</p>
<p>Bad data may come in the form of <em>outliers</em>, which are commonly defined based on their value with respect to the <em>distribution</em> of all values of the same variable in a dataset. Hence, their identification most commonly relies on quantifying their distance from the center of the variable’s empirical distribution. The default <code>boxplot()</code> plotting function in R (which we will learn about more in <a href="data_vis.html" class="quarto-xref"><span>Chapter 8</span></a>) shows the median (bold line in the center), the upper and lower quartiles (corresponding to the 25% and the 75% quantiles, often referred to as <span class="math inline">\(Q_1\)</span> and <span class="math inline">\(Q_3\)</span> , given by the upper and lower edge of the box plot) and the range of <span class="math inline">\(( Q_1 - 1.5 (Q_3 - Q_1), Q_3 + 1.5 (Q_3 - Q_1))\)</span>. Any point outside this range is plotted by a circle and labeled an “outlier”. However, this definition is very restrictive and may lead to a false labeling of outliers, in particular if they are drawn from a distribution with a fat tail or from asymmetrical distributions.</p>
<p>Outliers may also be identified via multivariate distributions. We will re-visit such methods later, in <a href="regression_classification.html" class="quarto-xref"><span>Chapter 9</span></a>. For certain applications, outliers or <em>anomalies</em> may be the target of the investigation, not the noise in the data. This has spurred the field of <a href="https://en.wikipedia.org/wiki/Anomaly_detection"><em>anomaly detection</em></a> which relies on machine learning algorithms for determining whether a value is anomalous, given a set of covariates.</p>
<p>Sensor error or algorithm error may generate spurious values, identified, for example when a continuous variable attains the numerically identical value with a spuriously high frequency.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes<span class="sc">$</span>GPP_NT_VUT_REF <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">|&gt;</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sort</span>(<span class="at">decreasing =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 5.18422  3.54996   1.3107 -5.57199 0.984756  2.49444 
      32       22       19       18       17       17 </code></pre>
</div>
</div>
<p>The probability of a certain numeric value of a continuous variable to appear twice in a dataset is practically zero. Here, several values appear multiple times - the value <code>5.18422</code> even 32 times! This must be bad data.</p>
<p>Other processes may lead to spurious trends or <em>drift</em> in the data, for example caused by sensor degradation. Spurious <em>step changes</em> or <em>change points</em> in time series or in (multivariate) regressions may be related to the replacement or deplacement of the measuring device. Different methods and R libraries help identifying such cases (see for example <a href="https://www.marinedatascience.co/blog/2019/09/28/comparison-of-change-point-detection-methods/">this</a> tutorial). Solutions have to be found for the remediation of such spurious patterns in the data on a case-by-case basis.</p>
</section>
<section id="handling-missing-data" class="level4" data-number="7.3.10.3">
<h4 data-number="7.3.10.3" class="anchored" data-anchor-id="handling-missing-data"><span class="header-section-number">7.3.10.3</span> Handling missing data</h4>
<p>The question about when data are “bad” and whether to remove it is often critical. Such decisions are important to keep track of and should be reported as transparently as possible in publications. In reality, where the data generation process may start in the field with actual human beings writing notes in a lab book, and where the human collecting the data is often not the same as the human analyzing the data or writing the paper, it’s often more difficult to keep track of such decisions. As a general principle, it is advisable to design data records such that decisions made during the data collection process remain transparent throughout all stages of the workflow and that sufficient information be collected to enable later revisions of particularly critical decisions. In practice, this means that the removal of data and entire rows should be avoided and implemented only at the very last step if necessary (e.g., when passing the data into a model fitting function). Instead, information about whether data are bad should be kept in a separate, categorical, variable (a <em>quality control</em> variable, like <code>*_QC</code> variables in our example data <code>half_hourly_fluxes</code>).</p>
<p>Data may be missing for several reasons. Some yield random patterns of missing data, others not. In the latter case, we can speak of <em>informative missingness</em> (<a href="http://www.feat.engineering/">Kuhn and Johnson, 2019</a>) and its information can be used for modelling. For categorical data, we may replace such data with <code>"none"</code> (instead of <code>NA</code>). Some machine learning algorithms (mainly tree-based methods, e.g., Random Forest) can handle missing values. However, when comparing the performance of alternative ML algorithms, they should be tested with the same data and removing missing data should be done beforehand.</p>
<p>Most machine learning algorithms require missing values to be removed. That is, if any of the cells in one row has a missing value, the entire cell gets removed. This generally leads to a loss of information contained in the remaining variables. Methods exist to <em>impute</em> missing values in order to avoid this information loss. However, the gain of data imputation has to be traded off against effects of associating the available variables with the imputed (knowingly wrong) values, and effects of <em>data leakage</em> have to be considered. Data imputation as part of the modelling process will be dealt with in <a href="supervised_ml_I.html" class="quarto-xref"><span>Chapter 10</span></a>.</p>
<p>In our example dataset, some values of <code>SWC_F_MDS_*</code> are given as <code>-9999</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="sc">|&gt;</span> </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(TIMESTAMP_START, <span class="fu">starts_with</span>(<span class="st">"SWC_F_MDS_"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  TIMESTAMP_START     SWC_F_MDS_1 SWC_F_MDS_2 SWC_F_MDS_3 SWC_F_MDS_4
  &lt;dttm&gt;                    &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
1 2004-01-01 00:00:00       -9999       -9999       -9999       -9999
2 2004-01-01 00:30:00       -9999       -9999       -9999       -9999
3 2004-01-01 01:00:00       -9999       -9999       -9999       -9999
4 2004-01-01 01:30:00       -9999       -9999       -9999       -9999
5 2004-01-01 02:00:00       -9999       -9999       -9999       -9999
6 2004-01-01 02:30:00       -9999       -9999       -9999       -9999
# ℹ 4 more variables: SWC_F_MDS_1_QC &lt;dbl&gt;, SWC_F_MDS_2_QC &lt;dbl&gt;,
#   SWC_F_MDS_3_QC &lt;dbl&gt;, SWC_F_MDS_4_QC &lt;dbl&gt;</code></pre>
</div>
</div>
<p>When reading the documentation of this specific dataset, we learn that <code>-9999</code> is the code for <em>missing data</em>. The {dplyr} functions help us to clarify these missing values by mutating across all numeric variables and overwrite entries with <code>NA</code> if they hold a <code>-9999</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="ot">&lt;-</span> half_hourly_fluxes <span class="sc">|&gt;</span>  </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span><span class="fu">na_if</span>(., <span class="sc">-</span><span class="dv">9999</span>)))</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="sc">|&gt;</span> </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(TIMESTAMP_START, <span class="fu">starts_with</span>(<span class="st">"SWC_F_MDS_"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  TIMESTAMP_START     SWC_F_MDS_1 SWC_F_MDS_2 SWC_F_MDS_3 SWC_F_MDS_4
  &lt;dttm&gt;                    &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
1 2004-01-01 00:00:00          NA          NA          NA          NA
2 2004-01-01 00:30:00          NA          NA          NA          NA
3 2004-01-01 01:00:00          NA          NA          NA          NA
4 2004-01-01 01:30:00          NA          NA          NA          NA
5 2004-01-01 02:00:00          NA          NA          NA          NA
6 2004-01-01 02:30:00          NA          NA          NA          NA
# ℹ 4 more variables: SWC_F_MDS_1_QC &lt;dbl&gt;, SWC_F_MDS_2_QC &lt;dbl&gt;,
#   SWC_F_MDS_3_QC &lt;dbl&gt;, SWC_F_MDS_4_QC &lt;dbl&gt;</code></pre>
</div>
</div>
<p>This lets us visualise the data and its gaps with <code>vis_miss()</code> from the {visdat} package. Visualising missing data can be informative for making decisions about dropping rows with missing data versus removing predictors from the analysis (which would imply too much data removal).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>visdat<span class="sc">::</span><span class="fu">vis_miss</span>(</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  half_hourly_fluxes <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>),</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster =</span> <span class="cn">FALSE</span>, </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">warn_large_data =</span> <span class="cn">FALSE</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data_wrangling_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For many applications, we want to filter the data so that the values of particular variables satisfy certain conditions. The {dplyr} function used for such tasks is <code>filter()</code>. As argument, it takes the expressions that specify the criterion for filtering using logical operators (<code>&gt;, &gt;=, &lt;, ==, !-, ...</code>, see <a href="primers.html" class="quarto-xref"><span>Chapter 2</span></a>). Multiple filtering criteria can be combined with logical (boolean) operators:</p>
<ul>
<li><code>&amp;</code>: logical AND</li>
<li><code>|</code>: logical OR</li>
<li><code>!</code> logical NOT</li>
</ul>
<p>For example, if we wanted only those rows in our data where NEE is based on measured or good quality gap-filled NEE data, we write:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NEE_VUT_REF_QC <span class="sc">==</span> <span class="dv">0</span> <span class="sc">|</span> NEE_VUT_REF_QC <span class="sc">==</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For evaluating multiple OR operations simultaneously, we can write alternatively and equivalently:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="sc">|&gt;</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NEE_VUT_REF_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that <code>filter()</code> removes entire rows. In some cases this is undesired and it is preferred to replace bad quality values with <code>NA</code>. It is important to note that specifying a value as missing is information itself. Dropping an entire row leads to the loss of this information. For cases where we do not want to drop entire rows when applying <code>filter()</code>, we can just replace certain values with <code>NA</code>. In our case, where we want to retain only data where NEE is based on actual measurements or good quality gap-filling, we can do this by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="sc">|&gt;</span> </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">GPP_NT_VUT_REF =</span> <span class="fu">ifelse</span>(NEE_VUT_REF_QC <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), GPP_NT_VUT_REF, <span class="cn">NA</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we decide to drop a row containing <code>NA</code> in any of the variables later during the workflow, we can do this, for example using the useful {tidyr} function <code>drop_na()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>half_hourly_fluxes <span class="sc">|&gt;</span> </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>An excellent source for a more comprehensive introduction to missing data handling is given in <a href="https://bookdown.org/max/FES/handling-missing-data.html">Kuhn and Johnson (2019)</a>.</p>
</section>
</section>
<section id="writing-data-to-csv" class="level3" data-number="7.3.11">
<h3 data-number="7.3.11" class="anchored" data-anchor-id="writing-data-to-csv"><span class="header-section-number">7.3.11</span> Writing data to CSV</h3>
<p>After having applied some data reduction and cleaning steps above, let’s save the data frame in the form of a CSV file for use in later chapters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(half_hourly_fluxes, <span class="at">file =</span> <span class="st">"data/FLX_CH-Lae_FLUXNET2015_FULLSET_HH_2004-2006_CLEAN.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Note: Making a file publicly available as a <code>.rds</code> file (explained in <a href="primers.html" class="quarto-xref"><span>Chapter 2</span></a>) violates the open science principles (introduced in <a href="open_science.html" class="quarto-xref"><span>Chapter 5</span></a>). These two formats make it very easy to save R objects related to your analysis project, but are not adequate to publicly share <em>data</em>. Therefore, whenever possible, save your data in a format that is readable across platforms without requiring proprietary software. Hence use <code>write_csv()</code> from {readr} whenever possible. We will encounter other non-proprietary formats that let you save and share more complex data structures in <a href="data_variety.html" class="quarto-xref"><span>Chapter 6</span></a>.</p>
</blockquote>
</section>
<section id="combining-relational-data" class="level3" data-number="7.3.12">
<h3 data-number="7.3.12" class="anchored" data-anchor-id="combining-relational-data"><span class="header-section-number">7.3.12</span> Combining relational data</h3>
<p>Often, data are spread across multiple files and tables and need to be combined for the planned analysis. In the simplest case, data frames have an identical number of columns, arranged in the same order, and we can “stack” them along rows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>co2_conc_subset_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  month `1959` `1960` `1961`
  &lt;ord&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1 Jan     315.   316.   317.
2 Feb     316.   317.   318.
3 Mar     316.   317.   318.
4 Apr     318.   319.   319.
5 May     318.   320.   320.
6 Jun     318    319.   320.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>co2_conc_subset_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  month `1959` `1960` `1961`
  &lt;ord&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1 Jul     316.   318.   318.
2 Aug     315.   316.   317.
3 Sep     314.   314    315.
4 Oct     313.   314.   315.
5 Nov     315.   315.   316.
6 Dec     315.   316.   317.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(co2_conc_subset_1, co2_conc_subset_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 4
   month `1959` `1960` `1961`
   &lt;ord&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 Jan     315.   316.   317.
 2 Feb     316.   317.   318.
 3 Mar     316.   317.   318.
 4 Apr     318.   319.   319.
 5 May     318.   320.   320.
 6 Jun     318    319.   320.
 7 Jul     316.   318.   318.
 8 Aug     315.   316.   317.
 9 Sep     314.   314    315.
10 Oct     313.   314.   315.
11 Nov     315.   315.   316.
12 Dec     315.   316.   317.</code></pre>
</div>
</div>
<p>In other cases, data frames may have an identical set of rows (and arranged in the same order) and we can “stack” them along columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>co2_conc_subset_3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
   month `1959` `1960`
   &lt;ord&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 Jan     315.   316.
 2 Feb     316.   317.
 3 Mar     316.   317.
 4 Apr     318.   319.
 5 May     318.   320.
 6 Jun     318    319.
 7 Jul     316.   318.
 8 Aug     315.   316.
 9 Sep     314.   314 
10 Oct     313.   314.
11 Nov     315.   315.
12 Dec     315.   316.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>co2_conc_subset_4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   month `1961`
   &lt;ord&gt;  &lt;dbl&gt;
 1 Jan     317.
 2 Feb     318.
 3 Mar     318.
 4 Apr     319.
 5 May     320.
 6 Jun     320.
 7 Jul     318.
 8 Aug     317.
 9 Sep     315.
10 Oct     315.
11 Nov     316.
12 Dec     317.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_cols</span>(co2_conc_subset_3, co2_conc_subset_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `month` -&gt; `month...1`
• `month` -&gt; `month...4`</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 5
   month...1 `1959` `1960` month...4 `1961`
   &lt;ord&gt;      &lt;dbl&gt;  &lt;dbl&gt; &lt;ord&gt;      &lt;dbl&gt;
 1 Jan         315.   316. Jan         317.
 2 Feb         316.   317. Feb         318.
 3 Mar         316.   317. Mar         318.
 4 Apr         318.   319. Apr         319.
 5 May         318.   320. May         320.
 6 Jun         318    319. Jun         320.
 7 Jul         316.   318. Jul         318.
 8 Aug         315.   316. Aug         317.
 9 Sep         314.   314  Sep         315.
10 Oct         313.   314. Oct         315.
11 Nov         315.   315. Nov         316.
12 Dec         315.   316. Dec         317.</code></pre>
</div>
</div>
<p>But beware! In particular the stacking along columns (<code>bind_cols()</code>) is very error-prone and should be avoided. Since a <em>tidy</em> data frame regards each row as an instance of associated measurements, the rows of the two data frames and their order must match exactly. Otherwise, an error is raised or (even worse) rows get associated when they shouldn’t be. In such cases, where information about a common set of observations is distributed across multiple data objects, we are dealing with <em>relational data</em>. The key for their combination (or “merging”) is the <em>join variable</em> - the column that is present in both data frames and which contains values along which the merging of the two data frames is performed. In our example from above, this is <code>month</code>, and we can use the {dplyr} function <code>left_join()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>co2_conc_subset_3 <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">n</span>(), <span class="at">replace =</span> <span class="cn">FALSE</span>)) <span class="sc">|&gt;</span>  <span class="co"># re-shuffling rows</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(co2_conc_subset_4, <span class="at">by =</span> <span class="st">"month"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(month)  <span class="co"># sort in ascending order</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 4
   month `1959` `1960` `1961`
   &lt;ord&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 Jan     315.   316.   317.
 2 Feb     316.   317.   318.
 3 Mar     316.   317.   318.
 4 Apr     318.   319.   319.
 5 May     318.   320.   320.
 6 Jun     318    319.   320.
 7 Jul     316.   318.   318.
 8 Aug     315.   316.   317.
 9 Sep     314.   314    315.
10 Oct     313.   314.   315.
11 Nov     315.   315.   316.
12 Dec     315.   316.   317.</code></pre>
</div>
</div>
<p>Note that here, we first re-shuffled (permuted) the rows of <code>df6</code> for demonstration purposes, and arranged the output data frame again by <code>month</code> - an ordinal variable. <code>left_join()</code> is not compromised by the order of the rows, but instead relies on the join variable, specified by the argument <code>by = "month"</code>, for associating (merging, joining) the two data frames. In some cases, multiple columns may act as the joining variables in their combination (for example <code>by = c("year", "month")</code>).</p>
<p>Other variants of <code>*_join()</code> are available as described <a href="https://r4ds.had.co.nz/relational-data.html">here</a>.</p>
</section>
</section>
<section id="sec-extramaterialwrangling" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="sec-extramaterialwrangling"><span class="header-section-number">7.4</span> Extra material</h2>
<section id="functional-programming-i" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="functional-programming-i"><span class="header-section-number">7.4.1</span> Functional programming I</h3>
<p>Above, we read a CSV table into R and applied several data transformation steps. In practice, we often have to apply the same data transformation steps repeatedly over a set of similar objects. This <em>extra material</em> section outlines an example workflow for demonstrating how to efficiently work with lists of similar objects - in particular, lists of data frames.</p>
<p>Our aim is to read a set of files into R data frames and apply transformation steps to each data frame separately. Here, we will work with daily data, not half-hourly data. The daily data contains largely identical variables with consistent naming and units as in the half-hourly data (description above). Let’s start by creating a list of paths that point to the files with daily data. They are all located in the directory <code>"./data"</code> and share a certain string of characters in their file names <code>"_FLUXNET2015_FULLSET_DD_"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>vec_files <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="st">"./data"</span>, <span class="at">pattern =</span> <span class="st">"_FLUXNET2015_FULLSET_DD_"</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(vec_files)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "./data/FLX_CH-Dav_FLUXNET2015_FULLSET_DD_1997-2014_1-3.csv"
[2] "./data/FLX_CH-Lae_FLUXNET2015_FULLSET_DD_2004-2014_1-4.csv"
[3] "./data/FLX_FI-Hyy_FLUXNET2015_FULLSET_DD_1996-2014_1-3.csv"
[4] "./data/FLX_FR-Pue_FLUXNET2015_FULLSET_DD_2000-2014_2-3.csv"</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>To reproduce this code chunk, you can download the files <code>FLX_CH-Lae_FLUXNET2015_FULLSET_HH_2004-2006.csv</code> from <a href="https://github.com/geco-bern/agds_book/tree/main/book/data">here</a> and read it from the local path where the file is stored on your machine.</p>
</blockquote>
<p><code>vec_files</code> is now a vector of three files paths as character strings. To read in the three files and combine the three data frames (<code>list_df</code> below) into a list of data frames, we could use a <code>for</code> loop:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>list_df <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (ifil <span class="cf">in</span> vec_files){</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  list_df[[ifil]] <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(ifil)</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Repeatedly applying a function (here <code>read_csv()</code>) over a list similar objects is facilitated by the <code>map*()</code> family of functions from the {purrr} package. An (almost) equivalent statement is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>list_df <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map</span>(<span class="fu">as.list</span>(vec_files), <span class="sc">~</span><span class="fu">read_csv</span>(.))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here, <code>purrr::map()</code> applies the function <code>read_csv()</code> to elements of a <em>list</em>. Hence, we first have to convert the vector <code>vec_files</code> to a list. A list is always the first argument within the <code>purrr::map()</code> function. Note two new symbols (<code>~</code> and <code>.</code>). The <code>~</code> always goes before the function that is repeatedly applied (or “mapped”) to elements of the list. The <code>.</code> indicates where the elements of the list would go if spelled out (e.g., here, <code>read_csv(.)</code> would be <code>read_csv("./data/FLX_CH-Dav_FLUXNET2015_FULLSET_DD_1997-2014_1-3.csv")</code> for the first iteration). The output of <code>purrr::map()</code> is again a list. There are many variants of the function <code>purrr::map()</code> that each have a specific use. A complete reference for all {purrr} functions is available <a href="https://purrr.tidyverse.org/reference/index.html">here</a>. A useful and more extensive tutorial on {purrr} is available <a href="https://www.r-bloggers.com/one-stop-tutorial-on-purrr-package-in-r/">here</a>.</p>
<p>The above <code>purrr::map()</code> call does not return a <em>named</em> list as our <code>for</code> loop created. But we can give each element of the returned list of data frames different names by:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(list_df) <span class="ot">&lt;-</span> vec_files  <span class="co"># this makes it a named list</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we will apply a similar data cleaning procedure to this data set as we did above for half-hourly data. To do so, we “package” the individual cleaning steps into a function …</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># function definition</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>clean_data_dd <span class="ot">&lt;-</span> <span class="cf">function</span>(df){</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># select only the variables we are interested in</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>      TIMESTAMP,</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ends_with</span>(<span class="st">"_F"</span>),</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>      GPP_NT_VUT_REF,</span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>      NEE_VUT_REF_QC,</span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">starts_with</span>(<span class="st">"SWC_F_MDS_"</span>),</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>      <span class="sc">-</span><span class="fu">contains</span>(<span class="st">"JSB"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># convert to a nice date object</span></span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">TIMESTAMP =</span> lubridate<span class="sc">::</span><span class="fu">ymd</span>(TIMESTAMP)) <span class="sc">|&gt;</span></span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-18"><a href="#cb76-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># set all -9999 to NA</span></span>
<span id="cb76-19"><a href="#cb76-19" aria-hidden="true" tabindex="-1"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span><span class="fu">na_if</span>(., <span class="sc">-</span><span class="dv">9999</span>)))</span>
<span id="cb76-20"><a href="#cb76-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb76-21"><a href="#cb76-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df)</span>
<span id="cb76-22"><a href="#cb76-22" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>… and apply this function to each data frame within our list of data frames:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>list_df <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map</span>(list_df, <span class="sc">~</span><span class="fu">clean_data_dd</span>(.))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Having different data frames as elements of a list may be impractical. Since we read in similarly formatted files and selected always the same variables in each data frame, all elements of the list of data frames <code>list_df</code> share the same columns. This suggests that we can collapse our list of data frames and “stack” data frames along rows. As described above, this can be done using <code>bind_rows()</code> and we can automatically create a new column <code>"siteid"</code> in the stacked data frame that takes the name of the corresponding list element.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>daily_fluxes_allsites <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(list_df, <span class="at">.id =</span> <span class="st">"siteid"</span>)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>daily_fluxes_allsites</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23,011 × 21
   siteid              TIMESTAMP    TA_F SW_IN_F LW_IN_F VPD_F  PA_F   P_F  WS_F
   &lt;chr&gt;               &lt;date&gt;      &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 ./data/FLX_CH-Dav_… 1997-01-01 -4.57     77.4    223. 0.565  82.6   0.4 0.559
 2 ./data/FLX_CH-Dav_… 1997-01-02 -3.34     45.6    235. 0.978  82.9   0   1.11 
 3 ./data/FLX_CH-Dav_… 1997-01-03  0.278    74.1    239. 2.24   82.4   0   2.03 
 4 ./data/FLX_CH-Dav_… 1997-01-04 -1.88     58.1    250. 1.38   81.7   1.8 1.92 
 5 ./data/FLX_CH-Dav_… 1997-01-05 -4.96     80.8    248. 1.16   82.3   0   0.407
 6 ./data/FLX_CH-Dav_… 1997-01-06 -4.48     59.6    237. 0.838  82.7   0   0.466
 7 ./data/FLX_CH-Dav_… 1997-01-07 -3.15     45.5    234. 1.33   82.9   0   1.03 
 8 ./data/FLX_CH-Dav_… 1997-01-08 -2.45     76.7    222. 1.87   82.7   0   1.95 
 9 ./data/FLX_CH-Dav_… 1997-01-09 -2.43     47.6    251. 1.44   82.2   0   0.785
10 ./data/FLX_CH-Dav_… 1997-01-10 -3.09     39.6    242. 0.776  82.8   0   1.25 
# ℹ 23,001 more rows
# ℹ 12 more variables: GPP_NT_VUT_REF &lt;dbl&gt;, NEE_VUT_REF_QC &lt;dbl&gt;,
#   SWC_F_MDS_1 &lt;dbl&gt;, SWC_F_MDS_2 &lt;dbl&gt;, SWC_F_MDS_3 &lt;dbl&gt;,
#   SWC_F_MDS_1_QC &lt;dbl&gt;, SWC_F_MDS_2_QC &lt;dbl&gt;, SWC_F_MDS_3_QC &lt;dbl&gt;,
#   SWC_F_MDS_4 &lt;dbl&gt;, SWC_F_MDS_4_QC &lt;dbl&gt;, SWC_F_MDS_5 &lt;dbl&gt;,
#   SWC_F_MDS_5_QC &lt;dbl&gt;</code></pre>
</div>
</div>
<p>A visualisation of missing data indicates that soil water content data (<code>SWC_F_MDS_*</code>) are often missing.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a subset of the data</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>daily_fluxex_subset <span class="ot">&lt;-</span> daily_fluxes_allsites <span class="sc">|&gt;</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="co"># visualize missing data</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>visdat<span class="sc">::</span><span class="fu">vis_miss</span>(</span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>  daily_fluxex_subset,</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster =</span> <span class="cn">FALSE</span>,</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">warn_large_data =</span> <span class="cn">FALSE</span></span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data_wrangling_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-strings" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="sec-strings"><span class="header-section-number">7.4.2</span> Strings</h3>
<p>The column <code>siteid</code> currently contains strings specifying the full paths of the files that were read in earlier. The next task is to extract the site name from these strings. The file names follow a clear pattern (this also highlights why naming files wisely can often make life a lot simpler).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>daily_fluxes_allsites<span class="sc">$</span>siteid <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "./data/FLX_CH-Dav_FLUXNET2015_FULLSET_DD_1997-2014_1-3.csv"
[2] "./data/FLX_CH-Dav_FLUXNET2015_FULLSET_DD_1997-2014_1-3.csv"
[3] "./data/FLX_CH-Dav_FLUXNET2015_FULLSET_DD_1997-2014_1-3.csv"
[4] "./data/FLX_CH-Dav_FLUXNET2015_FULLSET_DD_1997-2014_1-3.csv"
[5] "./data/FLX_CH-Dav_FLUXNET2015_FULLSET_DD_1997-2014_1-3.csv"
[6] "./data/FLX_CH-Dav_FLUXNET2015_FULLSET_DD_1997-2014_1-3.csv"</code></pre>
</div>
</div>
<p>The paths each start with the subdirectory where they are located (<code>"./data/"</code>), then <code>"FLX_"</code>, followed by the site name (the first three entries of the table containing data from all sites are for the site <code>"CH-Dav"</code>), and then some more specifications, including the years that respective files’ data cover.</p>
<p>The <a href="https://stringr.tidyverse.org/">{stringr}</a> package (part of tidyverse) offers a set of functions for working with strings. <a href="https://r4ds.had.co.nz/strings.html">Wikham and Grolemund (2017)</a> provide a more comprehensive introduction to working with strings. Here, we would like to extract the six characters, starting at position 12. The function <code>str_sub()</code> does that job.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>vec_sites <span class="ot">&lt;-</span> <span class="fu">str_sub</span>(vec_files, <span class="at">start =</span> <span class="dv">12</span>, <span class="at">end =</span> <span class="dv">17</span>)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(vec_sites)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CH-Dav" "CH-Lae" "FI-Hyy" "FR-Pue"</code></pre>
</div>
</div>
<p>We can use this function to mutate all values of column <code>"siteid"</code>, overwriting it with just these six characters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>daily_fluxes_allsites <span class="ot">&lt;-</span> daily_fluxes_allsites <span class="sc">|&gt;</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">siteid =</span> <span class="fu">str_sub</span>(siteid, <span class="at">start =</span> <span class="dv">12</span>, <span class="at">end =</span> <span class="dv">17</span>))</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>daily_fluxes_allsites</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23,011 × 21
   siteid TIMESTAMP    TA_F SW_IN_F LW_IN_F VPD_F  PA_F   P_F  WS_F
   &lt;chr&gt;  &lt;date&gt;      &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 CH-Dav 1997-01-01 -4.57     77.4    223. 0.565  82.6   0.4 0.559
 2 CH-Dav 1997-01-02 -3.34     45.6    235. 0.978  82.9   0   1.11 
 3 CH-Dav 1997-01-03  0.278    74.1    239. 2.24   82.4   0   2.03 
 4 CH-Dav 1997-01-04 -1.88     58.1    250. 1.38   81.7   1.8 1.92 
 5 CH-Dav 1997-01-05 -4.96     80.8    248. 1.16   82.3   0   0.407
 6 CH-Dav 1997-01-06 -4.48     59.6    237. 0.838  82.7   0   0.466
 7 CH-Dav 1997-01-07 -3.15     45.5    234. 1.33   82.9   0   1.03 
 8 CH-Dav 1997-01-08 -2.45     76.7    222. 1.87   82.7   0   1.95 
 9 CH-Dav 1997-01-09 -2.43     47.6    251. 1.44   82.2   0   0.785
10 CH-Dav 1997-01-10 -3.09     39.6    242. 0.776  82.8   0   1.25 
# ℹ 23,001 more rows
# ℹ 12 more variables: GPP_NT_VUT_REF &lt;dbl&gt;, NEE_VUT_REF_QC &lt;dbl&gt;,
#   SWC_F_MDS_1 &lt;dbl&gt;, SWC_F_MDS_2 &lt;dbl&gt;, SWC_F_MDS_3 &lt;dbl&gt;,
#   SWC_F_MDS_1_QC &lt;dbl&gt;, SWC_F_MDS_2_QC &lt;dbl&gt;, SWC_F_MDS_3_QC &lt;dbl&gt;,
#   SWC_F_MDS_4 &lt;dbl&gt;, SWC_F_MDS_4_QC &lt;dbl&gt;, SWC_F_MDS_5 &lt;dbl&gt;,
#   SWC_F_MDS_5_QC &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="functional-programming-ii" class="level3" data-number="7.4.3">
<h3 data-number="7.4.3" class="anchored" data-anchor-id="functional-programming-ii"><span class="header-section-number">7.4.3</span> Functional programming II</h3>
<p>Functions can be applied to a list of objects of any type. Therefore, <code>purrr::map()</code> is a powerful approach to “iterating” over multiple instances of the same object type and can be used for all sorts of tasks. In the following, list elements are data frames of daily data and the function <code>lm()</code> fits a linear regression model of GPP versus shortwave radiation to each sites’ data. We’ll learn more about fitting statistical models in R in <a href="regression_classification.html" class="quarto-xref"><span>Chapter 9</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>list_linmod <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map</span>(list_df, <span class="sc">~</span><span class="fu">lm</span>(GPP_NT_VUT_REF <span class="sc">~</span> SW_IN_F, <span class="at">data =</span> .))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note how the <code>.</code> indicates where the elements of <code>list_df</code> go when evaluating the <code>lm()</code> function. This returns a list of linear model objects (the type of objects returned by the <code>lm()</code> function call).</p>
<p>We can spin the functional programming concept further and apply (or map) the <code>summary()</code> function to the <code>lm</code>-model objects to get a list of useful statistics and metrics, and then further extract the element <code>"r.squared"</code> from that list as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>list_linmod <span class="sc">|&gt;</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  purrr<span class="sc">::</span><span class="fu">map</span>(summary) <span class="sc">|&gt;</span>  <span class="co"># apply the summary() function to each list element</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map_dbl</span>(<span class="st">"r.squared"</span>)    <span class="co"># extract R-squared from the list generated by summary()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>./data/FLX_CH-Dav_FLUXNET2015_FULLSET_DD_1997-2014_1-3.csv 
                                                 0.4201802 
./data/FLX_CH-Lae_FLUXNET2015_FULLSET_DD_2004-2014_1-4.csv 
                                                 0.5074248 
./data/FLX_FI-Hyy_FLUXNET2015_FULLSET_DD_1996-2014_1-3.csv 
                                                 0.6415685 
./data/FLX_FR-Pue_FLUXNET2015_FULLSET_DD_2000-2014_2-3.csv 
                                                 0.3772839 </code></pre>
</div>
</div>
<p><code>map_dbl()</code> is a variant of the <code>purrr::map()</code> function that returns not a list, but a vector of numeric values of class “double” (hence, the name <code>_dbl</code>). Note further, that providing a character (<code>"r.squared"</code>) as an argument instead of an (unquoted) function name, <code>purrr::map()</code> extracts the correspondingly named list element, instead of applying a function to a list element.</p>
<p>When writing code for an analysis, it’s useful, if not essential, to understand the objects we’re working with, understand its type and shape, and make sense of the results of simple <code>print &lt;object&gt;</code> statements. Data frames are particularly handy as they provide an organisation of data that is particularly intuitive (variables along columns, observations along rows, values in cells). Here, we’re dealing with a list of linear model objects. Can such a list fit into the paradigm of <em>tidy</em> data frames?</p>
<p>Yes, they can. Think of the linear model objects as ‘values’. Values don’t necessarily have to be scalars, but they can be of any type (class).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">siteid =</span> vec_sites,</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">linmod =</span> list_linmod</span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  siteid linmod      
  &lt;chr&gt;  &lt;named list&gt;
1 CH-Dav &lt;lm&gt;        
2 CH-Lae &lt;lm&gt;        
3 FI-Hyy &lt;lm&gt;        
4 FR-Pue &lt;lm&gt;        </code></pre>
</div>
</div>
<p>The fact that cells can contain any type of object offers a powerful concept. Instead of a linear model object as in the example above, each cell may even contain another data frame. In such a case, we say that the data frame is no longer <em>flat</em>, but <em>nested</em>.</p>
<p>The following creates a nested data frame, where the column <code>data</code> is defined by the list of data frames read from files above (<code>list_df</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">siteid =</span> vec_sites,</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> list_df</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  siteid data                 
  &lt;chr&gt;  &lt;named list&gt;         
1 CH-Dav &lt;tibble [6,574 × 16]&gt;
2 CH-Lae &lt;tibble [4,018 × 18]&gt;
3 FI-Hyy &lt;tibble [6,940 × 20]&gt;
4 FR-Pue &lt;tibble [5,479 × 10]&gt;</code></pre>
</div>
</div>
<p>We can achieve the same result by directly nesting the flat data frame holding all sites’ data (<code>daily_fluxes_allsites</code>). This is done by combining the <code>group_by()</code>, which we have encountered above when aggregating using <code>summarise()</code>, with the function <code>nest()</code> from the {tidyr} package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>daily_fluxes_allsites <span class="sc">|&gt;</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(siteid) <span class="sc">|&gt;</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
# Groups:   siteid [4]
  siteid data                 
  &lt;chr&gt;  &lt;list&gt;               
1 CH-Dav &lt;tibble [6,574 × 20]&gt;
2 CH-Lae &lt;tibble [4,018 × 20]&gt;
3 FI-Hyy &lt;tibble [6,940 × 20]&gt;
4 FR-Pue &lt;tibble [5,479 × 20]&gt;</code></pre>
</div>
</div>
<p>The function <code>nest()</code> names the nested data column automatically <code>"data"</code>.</p>
<p>This structure is very useful. For example, for applying functions over sites’ data frames separately (and not over the entire data frame). By combining <code>purrr::map()</code> and <code>mutate()</code>, we can fit linear models on each site’s data frame individually in one go.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>daily_fluxes_allsites <span class="sc">|&gt;</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(siteid) <span class="sc">|&gt;</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">|&gt;</span></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">linmod =</span> purrr<span class="sc">::</span><span class="fu">map</span>(data, <span class="sc">~</span><span class="fu">lm</span>(GPP_NT_VUT_REF <span class="sc">~</span> SW_IN_F, <span class="at">data =</span> .)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This approach is extremely powerful and lets you stick to working with tidy data frames and use the rows-dimension flexibly. Here, rows are sites and no longer time steps, while the nested data frames in column <code>"data"</code> have time steps along their rows. The power of nesting is also to facilitate complex aggregation steps over a specified dimension (or axis of variation, here given by <code>siteid</code>), where the aggregating function is not limited to taking a vector as input and returning a scalar, as is the case for applications of <code>summarise()</code> (see above).</p>
<p>Combining the steps described above into a single workflow, we have:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>daily_fluxes_allsites_nested <span class="ot">&lt;-</span> daily_fluxes_allsites <span class="sc">|&gt;</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(siteid) <span class="sc">|&gt;</span></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">|&gt;</span></span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">linmod =</span> purrr<span class="sc">::</span><span class="fu">map</span>(data, <span class="sc">~</span><span class="fu">lm</span>(GPP_NT_VUT_REF <span class="sc">~</span> SW_IN_F, <span class="at">data =</span> .))) <span class="sc">|&gt;</span></span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">summ =</span> purrr<span class="sc">::</span><span class="fu">map</span>(linmod, <span class="sc">~</span><span class="fu">summary</span>(.))) <span class="sc">|&gt;</span></span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">rsq =</span> <span class="fu">map_dbl</span>(summ, <span class="st">"r.squared"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb97-7"><a href="#cb97-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(rsq))  <span class="co"># to arrange output, with highest r-squared on top</span></span>
<span id="cb97-8"><a href="#cb97-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-9"><a href="#cb97-9" aria-hidden="true" tabindex="-1"></a>daily_fluxes_allsites_nested</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
# Groups:   siteid [4]
  siteid data                  linmod summ         rsq
  &lt;chr&gt;  &lt;list&gt;                &lt;list&gt; &lt;list&gt;     &lt;dbl&gt;
1 FI-Hyy &lt;tibble [6,940 × 20]&gt; &lt;lm&gt;   &lt;smmry.lm&gt; 0.642
2 CH-Lae &lt;tibble [4,018 × 20]&gt; &lt;lm&gt;   &lt;smmry.lm&gt; 0.507
3 CH-Dav &lt;tibble [6,574 × 20]&gt; &lt;lm&gt;   &lt;smmry.lm&gt; 0.420
4 FR-Pue &lt;tibble [5,479 × 20]&gt; &lt;lm&gt;   &lt;smmry.lm&gt; 0.377</code></pre>
</div>
</div>
<p>This code is a demonstration of the power of tidy and nested data frames and for the clarity of the {tidyverse} syntax.</p>
<p>Nesting is useful also for avoiding value duplication when joining relational data objects. Above, we nested time series data objects (where time steps and sites are both organised along rows) by sites and got a data frame where only sites are organised along rows, while time steps are nested inside the column <code>"data"</code>. This now fits the structure of a relational data object (<code>siteinfo_fluxnet2015</code>) containing site-specific meta information (also with only sites along rows).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>base<span class="sc">::</span><span class="fu">load</span>(<span class="st">"data/siteinfo_fluxnet2015.rda"</span>)  <span class="co"># loads siteinfo_fluxnet2015</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Joining the nested data frame with site meta information results in a substantially smaller and much handier data frame compared to an alternative, where the site meta information is joined into the un-nested (daily) data frame, and therefore duplicated for each day within sites.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>daily_fluxes_allsites_nested_joined <span class="ot">&lt;-</span> siteinfo_fluxnet2015 <span class="sc">|&gt;</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">siteid =</span> sitename) <span class="sc">|&gt;</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(</span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(daily_fluxes_allsites_nested, <span class="sc">-</span>linmod, <span class="sc">-</span>summ, <span class="sc">-</span>rsq),</span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="st">"siteid"</span></span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb100-7"><a href="#cb100-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-8"><a href="#cb100-8" aria-hidden="true" tabindex="-1"></a>daily_fluxes_allsites_joined <span class="ot">&lt;-</span> siteinfo_fluxnet2015 <span class="sc">|&gt;</span></span>
<span id="cb100-9"><a href="#cb100-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">siteid =</span> sitename) <span class="sc">|&gt;</span></span>
<span id="cb100-10"><a href="#cb100-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(</span>
<span id="cb100-11"><a href="#cb100-11" aria-hidden="true" tabindex="-1"></a>    daily_fluxes_allsites,</span>
<span id="cb100-12"><a href="#cb100-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="st">"siteid"</span></span>
<span id="cb100-13"><a href="#cb100-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb100-14"><a href="#cb100-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-15"><a href="#cb100-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Flat and joined:"</span>, </span>
<span id="cb100-16"><a href="#cb100-16" aria-hidden="true" tabindex="-1"></a>            <span class="fu">format</span>(<span class="fu">object.size</span>(daily_fluxes_allsites_joined),  </span>
<span id="cb100-17"><a href="#cb100-17" aria-hidden="true" tabindex="-1"></a>                   <span class="at">units =</span> <span class="st">"auto"</span>, </span>
<span id="cb100-18"><a href="#cb100-18" aria-hidden="true" tabindex="-1"></a>                   <span class="at">standard =</span> <span class="st">"SI"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Flat and joined: 5.8 MB"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Nested and joined:"</span>, </span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">format</span>(<span class="fu">object.size</span>(daily_fluxes_allsites_nested_joined),  </span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">units =</span> <span class="st">"auto"</span>, </span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">standard =</span> <span class="st">"SI"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Nested and joined: 3.7 MB"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># save for later use</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>  daily_fluxes_allsites_nested_joined,</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">"data/daily_fluxes_allsites_nested_joined.rds"</span></span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="exerciseswrangling" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="exerciseswrangling"><span class="header-section-number">7.5</span> Exercises</h2>
<blockquote class="blockquote">
<p><em>Hint</em>: For all exercises remember the resources we provided on finding help in section <a href="primers.html#sec-findinghelp" class="quarto-xref"><span>Section 2.12</span></a>.</p>
</blockquote>
<section id="star-wars" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="star-wars">Star wars</h3>
<p>{dplyr} comes with a toy dataset <code>dplyr::starwars</code> (just type it into the console to see its content). Have a look at the dataset with <code>View()</code>. Play around with the dataset to get familiar with the {tidyverse} coding style. Use (possibly among others) the functions <code>dplyr::filter()</code>, <code>dplyr::arrange()</code>, <code>dplyr::pull()</code>, <code>dplyr::select()</code>, <code>dplyr::desc()</code> and <code>dplyr::slice()</code> to answer the following questions:</p>
<ul>
<li>How many pale characters come from the planets Ryloth and Naboo?</li>
<li>Who is the oldest among the tallest thirty characters?</li>
<li>What is the name of the smallest character and their starship in “Return of the Jedi”</li>
</ul>
<blockquote class="blockquote">
<p>Hint: Use <code>unnest()</code> to expand columns that contain lists inside cells. The expansion of such columns creates additional rows in the data frame if the cell contained a list with more than one element.</p>
</blockquote>
</section>
<section id="aggregating" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="aggregating">Aggregating</h3>
<p>You have learned about aggregating in the {tidyverse}. Let’s put it in practice.</p>
<ul>
<li><p>Reuse the code in the tutorial to read, reduce, and aggregate the <code>half_hourly_fluxes</code> dataset to the daily scale, calculating the following metrics across half-hourly <code>VPD_F</code> values within each day: mean, 25% quantile, and 75% quantile.</p></li>
<li><p>Retain only the daily data for which the daily mean VPD is among the upper or the lower 10% quantiles.</p></li>
<li><p>Calculate the mean of the 25% and the mean of the 75% quantiles of half-hourly VPD within the upper and lower 10% quantiles of mean daily VPD.</p></li>
</ul>
</section>
<section id="patterns-in-data-quality" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="patterns-in-data-quality">Patterns in data quality</h3>
<p>The uncleaned dataset <code>FLX_CH-Lae_FLUXNET2015_FULLSET_HH_2004-2006.csv</code> holds half-hourly data that is sometimes of poor quality. Investigate whether NEE data quality is randomly spread across hours in a day by calculating the proportion of (i) actually measured data, (ii) good quality gap-filled data, (iii) medium quality data, and (iv) poor quality data within each hour-of-day (24 hours per day).</p>
<blockquote class="blockquote">
<p>Hint: <code>summarise(total = n())</code> aggregates by counting the number of values.</p>
</blockquote>
<blockquote class="blockquote">
<p>Hint: <code>summarise(count_0 = sum(x == 0))</code> aggregates by counting the number of values for which the evaluation is <code>TRUE</code>.</p>
</blockquote>
<p>Interpret your findings: Are the proportions evenly spread across hours in a day?</p>
<p>Perform an aggregation of the half-hourly GPP data (variable <code>GPP_NT_VUT_REF</code>) to daily means of the unmodified data read from file <code>FLX_CH-Lae_FLUXNET2015_FULLSET_HH_2004-2006.csv</code>, and from cleaned data where only measured (not gap-filled) data is kept. This yields two data frames with daily GPP data. Calculate the overall mean GPP for the two data frames (across all days in the data frame). Are the overall mean GPP values equal? If not, why?</p>
</section>
</section>
<section id="sec-retidy" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="sec-retidy"><span class="header-section-number">7.6</span> Report Exercise</h2>
<section id="analyzing-changes-in-soil-organic-matter-during-elevated-co_2-experiments" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="analyzing-changes-in-soil-organic-matter-during-elevated-co_2-experiments">Analyzing changes in soil organic matter during elevated CO<span class="math inline">\(_2\)</span> experiments</h3>
<p>Open Science requires that data underlying published research articles is made available upon publication of the article. A separate aspect is the format of the shared data. Is it provided in an open-access data format? How easy is it to use the data for your own analyses? In this exercise, you will encounter data that was made freely available, but not in an open access format. Although it is “nice-looking” data, you will encounter that it is not tidy.</p>
<p>In this exercise, you will investigate the data published by Groeningen et al.&nbsp;(2014), where they looked at how soil carbon stocks may change due to the anthropogenic increase in <span class="math inline">\(CO_2\)</span>. They gathered data on changes in the soil organic matter content from experiments where ecosystems were exposed to elevated CO<span class="math inline">\(_2\)</span> concentrations and your task is to have a high-level look at this dataset. So, perform the following steps:</p>
<ol type="1">
<li><p>Download the data file (<code>.xlsx</code>) from the Supplementary Material of the following paper: <em>Groenigen, Kees Jan van, Xuan Qi, Craig W. Osenberg, Yiqi Luo, and Bruce A. Hungate. “Faster Decomposition Under Increased Atmospheric CO2 Limits Soil Carbon Storage.” Science 344, no. 6183 (May 2, 2014): 508–9. <a href="https://doi.org/10.1126/science.1249534" class="uri">https://doi.org/10.1126/science.1249534</a>.</em></p></li>
<li><p>Manually clean the data in the tab “Database S1” and save it as a CSV file that can be read into R.</p>
<ul>
<li>“Database S1” contains data of soil organic carbon measurements in experiments, where ecosystems are exposed to ambient (low) and elevated (high) CO<span class="math inline">\(_2\)</span> concentrations. The mean soil organic carbon of multiple samples (“n”) is recorded within each experiment for different sample dates. Information is provided for the time in years since the start of the experiment (“Time (years)”). <!-- -   _Bonus (not part of the assessment): If you feel like challenging yourself, you could try cleaning the data directly within R and never touching Excel! Can you find a way to do this with `readxl::read_xlsx()`?_ --></li>
</ul></li>
<li><p>In RStudio, create RMarkdown file. Then, write your code into the R chunks of the file to aggregate the data per experiment and calculate the log-response ratio within each experiment, as specified below.</p>
<ul>
<li><p>A log-response ratio can be used to quantify the effect that a treatment (e.g., elevated CO<span class="math inline">\(_2\)</span>) can have on your target variable <span class="math inline">\(x\)</span> (e.g., soil organic matter content). The log-response ratio can be calculated as: <span class="math inline">\(\text{RR} = \ln \left( \frac{x_\text{elevated}}{x_\text{ambient}} \right)\)</span></p></li>
<li><p>Aggregate data across all experiments for different years since the start of the experiment, distinguishing an early phase (&lt;3 years since start), a mid-phase (3-6 years since start), and a late phase (&gt;6 years since start). Calculate the log-response ratio for each phase. Calculate the log-response ratio for each parallel observation of SOC under ambient and elevated CO<span class="math inline">\(_2\)</span>, and then aggregate log response ratios by taking their mean (and not the other way round).</p></li>
<li><p>Present your results as tables using the <code>knitr::kable()</code> function.</p></li>
<li><p><em>Tip: Depending on your Excel settings, your exported csv is separated using <code>,</code> or <code>;</code>. The <code>read_csv()</code> function only works with <code>,</code>. So, if your file is separated with <code>;</code>, either change the export settings or use <code>read_csv2()</code>.Where would it have been useful if more information had been available.</em></p></li>
</ul></li>
<li><p>Answer the following questions:</p>
<ul>
<li>What are the data that you are looking at?</li>
<li>What do you expect your analysis to show, what is your hypothesis? How should soil organic matter content change under elevated CO<span class="math inline">\(_2\)</span>?</li>
<li>Interpret your results after aggregating the data: What do your final numbers mean? Do they support your initial hypothesis? Why so, why not?</li>
<li><em>Tip: Skim the paper and its references to better understand the data and processes you are looking at!``</em></li>
</ul></li>
</ol>
</section>
<section id="deliverables-for-the-report" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="deliverables-for-the-report">Deliverables for the report</h3>
<p>A key learning of this course is that you know how to create reproducible workflows and we pay a lot of attention on this during the assessment. You will learn more about the specific aspects to do so in <a href="open_science.html" class="quarto-xref"><span>Chapter 5</span></a> and <a href="code_management.html" class="quarto-xref"><span>Chapter 4</span></a>. So, if the following instructions for submitting this report exercise may sound cryptic, hang tight! It will make more sense as you work through this course.</p>
<p>You have to submit all report exercises via your GitHub repository that you created in <a href="code_management.html#sec-setupreport" class="quarto-xref"><span>Section 4.3.0.2</span></a>. For now, save this report exercise as a RMarkdown file with the name <code>re_tidy.Rmd</code> and place that file in a sub-directory called <code>vignettes</code> (a directory is simply a folder), which is located in your project directory (in full notation that means save your RMarkdown as <code>./vignettes/re_tidy.Rmd</code>). Additionally, produce a HTML version of your solution by knitting your RMarkdown file (see the <code>Knit</code> command in the panel below the files tabs in RStudio). Save this HTML file in the same <code>vignettes</code> directory (<code>./vignettes/re_tidy.html</code>). For your cleaned dataset, pick a sensible name and put it into a sub-direcory called <code>./data</code>. As with all other report exercises, make sure that your work is reproducible, for example, by letting another student download your repository from GitHub and knit your RMarkdown files on their computer.</p>
<blockquote class="blockquote">
<p><strong>Important</strong>: Structure your RMarkdown so that you first load necessary libraries, load your data and then write down your solution. <strong>Remember to access files with relative paths and not with hard-coded paths</strong>. So, access your file via <code>here::here('data/tidy_data.csv</code>), where <code>here</code> starts at the position of your <code>.Rproj</code> file. <strong>Never</strong> write hard-coded paths that looks like this: <code>"~/Desktop/Studium/.../tidy_data.csv"</code> or <code>"C:/Users/.../tidy_data.csv"</code> (see <a href="reproducible_workflows.html" class="quarto-xref"><span>Chapter 3</span></a>).</p>
</blockquote>
<blockquote class="blockquote">
<p>Tip: Your results do not have to match the results from the paper. It is important that you make your code reproducible, aggregate the data as instructed, and interpret your results.</p>
</blockquote>
<blockquote class="blockquote">
<p>Tip: If you are new to using RMarkdown, check out this <a href="https://www.dataquest.io/blog/r-markdown-guide-cheatsheet/">guide</a>.</p>
</blockquote>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./data_variety.html" class="pagination-link" aria-label="Data variety">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data variety</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./data_vis.html" class="pagination-link" aria-label="Data visualisation">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Data visualisation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>